name: Update Poster Paths
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *' # Monthly, 3am UTC on the 1st day of the month
permissions:
  contents: write

jobs:
  update-poster-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check TMDb credentials
        run: |
          if [[ -z "${{ secrets.TMDB_API_KEY }}" && -z "${{ secrets.TMDB_BEARER_TOKEN }}" ]]; then
            echo "❌ ERROR: Neither TMDB_API_KEY nor TMDB_BEARER_TOKEN secret is configured."
            echo "Please add one of the following secrets to your repository:"
            echo "  - TMDB_API_KEY for TMDb v3 API access"
            echo "  - TMDB_BEARER_TOKEN for TMDb v4 API access"
            exit 1
          elif [[ -n "${{ secrets.TMDB_API_KEY }}" && -n "${{ secrets.TMDB_BEARER_TOKEN }}" ]]; then
            echo "ℹ️  Both TMDB_API_KEY and TMDB_BEARER_TOKEN are configured. Will use Bearer token."
          elif [[ -n "${{ secrets.TMDB_BEARER_TOKEN }}" ]]; then
            echo "✅ TMDB_BEARER_TOKEN is configured for v4 API access."
          else
            echo "✅ TMDB_API_KEY is configured for v3 API access."
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install node-fetch@2

      - name: Update posterPaths.js
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}
        run: |
          node .github/scripts/updatePosterPaths.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/posterPaths.js
          git commit -m "Update posterPaths.js with latest TMDb poster paths" || echo "No changes to commit"
          git push
