name: Update Poster Paths
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *' # Monthly, 3am UTC on the 1st day of the month
permissions:
  contents: write

jobs:
  update-poster-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate TMDb API key
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          if [ -z "$TMDB_API_KEY" ]; then
            echo "Error: TMDb API key secret is not set or empty."
            exit 1
          fi
          echo "TMDb API key secret is present."

      - name: Test TMDb API Connectivity
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          curl --fail --silent --show-error -H "Authorization: Bearer $TMDB_API_KEY" "https://api.themoviedb.org/3/configuration" > /dev/null
          echo "Successfully connected to TMDb API."

      - name: Install dependencies
        run: |
          npm ci

      - name: Test TMDb API key
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          node .github/scripts/testTmdbApi.js

      - name: Update posterPaths.js
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          node .github/scripts/updatePosterPaths.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/posterPaths.js
          git commit -m "Update posterPaths.js with latest TMDb poster paths" || echo "No changes to commit"
          git push
